apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaimcp-ingress
  annotations:
    # Use the ClusterIssuer we created
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    # Standard NGINX Ingress class
    kubernetes.io/ingress.class: "nginx"

    # Backend talks HTTP now
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  tls:
    - hosts:
        - mcpch.ai
        - pki.mcpch.ai
      secretName: chaimcp-tls
  rules:
    - host: mcpch.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaimcp
                port:
                  number: 80
    - host: pki.mcpch.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaimcp
                port:
                  number: 80
